version: '3.8'

services:
  grad-work-db:
    image: postgres:15-alpine
    container_name: grad_work_postgres_db  # Уникальное имя контейнера
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grad_work_db            # Уникальное имя базы данных для этого проекта
    ports:
      - "5433:5432"                        # СЛЕВА порт твоего компьютера (5433), СПРАВА порт внутри контейнера (5432)
    volumes:
      - grad_work_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  grad-work-redis:
    image: redis:alpine
    container_name: grad_work_redis        # Уникальное имя контейнера для Redis
    ports:
      - "6379:6379"                        # СЛЕВА порт твоего компьютера (6379), СПРАВА стандартный порт Redis (6379)
    volumes:
      - grad_work_redis_data:/data         # Персистентное хранилище для данных Redis
    restart: unless-stopped

volumes:
  grad_work_db_data:
  grad_work_redis_data: